export enum ActionId {
  LIST_APPEARED_FIRST_TIME = 'LIST_APPEARED_FIRST_TIME',

  FETCH_TICKER_START = 'FETCH_TICKER_START',
  FETCH_TICKER_SUCCESS = 'FETCH_TICKER_SUCCESS',
  FETCH_TICKER_ERROR = 'FETCH_TICKER_ERROR',

  SORT_TICKERS_START = 'SORT_TICKERS_START',
  SORT_TICKERS_DONE = 'SORT_TICKERS_DONE',
}
